name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Unit tests
      run: sbt test
    - name: Platform tests
      run: ./script/ci.sh "platform test"
    - name: Deploy to Staging
      run: ./script/ci.sh "deploy to staging"
    - name: Acceptance tests
      run: ./script/ci.sh "acceptance tests"
    - name: Deploy to Production
      run: ./script/ci.sh "deploy to production"
    - name: Post deploy tests
      run: ./script/ci.sh "test post-deploy"

