name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Unit tests
      run: sbt test
    - name: Platform tests
      run: sbt platform-test
    - name: Deploy to Staging
    - name: Acceptance tests
    - name: Deploy to Production
    - name: Post deploy tests
